server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pfe_ai
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: techinfo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  firebase-configuration-file:  e-location-dc97b-firebase-adminsdk-npft8-38cbfe0663.json

spring-doc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    operationsSorter: method
